### ISSUE TITLE
Any idea how to solve this ?

### ISSUE THREAD

**Issue by p3ps111** [j-e-k/pgoapi#108]
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 6))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admin\appdata\local\temp\pip-build-2c8f9j\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1103, in return_env
        [self.VCIncludes,
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 811, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 541, in VCInstallDir
        python_vc = self.ri.lookup(reg_path, 'installdir')
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 451, in lookup
        bkey = winreg.OpenKey(hkey, key, 0, winreg.KEY_READ)
    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admin\appdata\local\temp\pip-build-2c8f9j\pyproj\

**Comment by MePsyDuck** [comment]
Download and install this : https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by p3ps111** [comment]
got it stick on something else
---------------------
C:\Users\admin\Desktop\Pokemon stuff\pgoapi-master\pgoapi-master>python pokecli.py - 0
Traceback (most recent call last):
  File "pokecli.py", line 140, in <module>
    main()
  File "pokecli.py", line 102, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 6 column 7 (char 90)

**Comment by MePsyDuck** [comment]
use python pokecli.py -i 0
