### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by darkdeath561** [j-e-k/pgoapi#32]
I get this error when attempting to start the bot:

C:\Users\nhege\Desktop\pgoapi-master\pgoapi-master>python pokecli.py -i 0
Traceback (most recent call last):
  File "pokecli.py", line 37, in <module>
    from pgoapi import PGoApi
  File "C:\Users\nhege\Desktop\pgoapi-master\pgoapi-master\pgoapi\__init__.py", line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File "C:\Users\nhege\Desktop\pgoapi-master\pgoapi-master\pgoapi\pgoapi.py", line 36, in <module>
    from itertools import chain, imap
ImportError: cannot import name 'imap'

**Comment by set92** [comment]
You are using python 2.7?

**Comment by joychugh** [comment]
itertools.imap() is in Python 2, but not in Python 3.
