### ISSUE TITLE
Master does not start...

### ISSUE THREAD

**Issue by BoBeR182** [j-e-k/pgoapi#522]
Traceback (most recent call last):
  File "pokecli.py", line 37, in <module>
    from poketrainer.poketrainer import Poketrainer
  File "/home/bober/poketrainer/poketrainer/poketrainer.py", line 19, in <module>
    from pgoapi.exceptions import AuthException
  File "/home/bober/poketrainer/pgoapi/**init**.py", line 19, in <module>

  File "/home/bober/poketrainer/pgoapi/pgoapi.py", line 61, in <module>
  File "/home/bober/poketrainer/pgoapi/poke_utils.py", line 5, in <module>
  File "/home/bober/poketrainer/pgoapi/pokemon.py", line 7, in <module>
  File "/home/bober/poketrainer/pgoapi/game_master.py", line 42, in <module>
IOError: [Errno 2] No such file or directory: '/home/bober/poketrainer/GAME_MASTER_POKEMON_v0_2.tsv'

**Comment by rirze** [comment]
try to do a clean pull: copy your configs and do a fresh `git clone` into a new directory.

**Comment by Visualq** [comment]
Same problem, did a new checkout and got the following error:

python pokecli.py -i 0 -e /home/w/pbot3/libencrypt.so
Traceback (most recent call last):
  File "pokecli.py", line 83, in <module>
    main()
  File "pokecli.py", line 70, in main
    poketrainer = Poketrainer(args)
  File "/home/w/pbot3/poketrainer/poketrainer.py", line 77, in __init__
    self._load_api()
  File "/home/w/pbot3/poketrainer/poketrainer.py", line 155, in _load_api
    self.api.activate_signature(
  File "/home/w/pbot/src/pgoapi/pgoapi/pgoapi.py", line 128, in __getattr__
    raise AttributeError
AttributeError

**Comment by stolencatkarma** [comment]
this error is caused by leftover .pyc files. delete all pyc files and restart. It does work.
